version: 0.2
phases:
  install:
    commands:
      - echo "Install phase"
  pre_build:
    commands:
      - echo Login to Docker Hub
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - echo Login to ECR
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 299834554299.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - docker build -t frontend .
      - docker tag frontend:latest 299834554299.dkr.ecr.ap-south-1.amazonaws.com/simple-docker-service-069bab0d86a7:latest
  post_build:
    commands:
      - docker push 299834554299.dkr.ecr.ap-south-1.amazonaws.com/simple-docker-service-069bab0d86a7:latest
      - aws ssm send-command --instance-ids i-03e9d5b43e5b14ad2 --document-name AWS-RunShellScript --region ap-south-1 --parameters 'commands=["aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 299834554299.dkr.ecr.ap-south-1.amazonaws.com","docker pull 299834554299.dkr.ecr.ap-south-1.amazonaws.com/simple-docker-service-069bab0d86a7:latest","docker stop frontend || true","docker rm frontend || true","docker run -d --name frontend -p 80:80 299834554299.dkr.ecr.ap-south-1.amazonaws.com/simple-docker-service-069bab0d86a7:latest"]'
